spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uwaas_service
    username: postgres
    password: 1qazxsw2

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public